language: ruby
rvm:
- 2.2.0
sudo: false
before_install:
  - git config --global user.name "Travis CI - Charles"
  - git config --global user.email "ch007m@gmail.com"
script: bundle exec rake deploy
env:
  global:
    secure: dshWtjkFtt3AIx+gfMJ+A+zBGzCpyBUR/sYfcSJD4jbvKYpzsHR900c+E1kMZBw01gBgdMoyZ5qxx7BnvzKh+Qq9p7IkSvnSlVNAAWlJjwgiO5Dq99o7QdifLi1SJHE7zOXJ08krCiYaF0GeU8oPsV/KuJnV2ymvrnCME3g+joN9KlGTxrK+pAuJWQXj4/8UnBErxtA54LAQ2ENY1h/24OjcgZ1q77qGSt8VkIQw1EZFxYhDjXkuzGNYzJVCSzXZYZVWYF0VVBke6V32an0uhKkTXD2PaVUU+t2CNqcUxCrTydHvTvHBtEcP0k4b5OYO6zZOS8JNaHkBzRswCyGtpFtPrPQgHLDfJP1uBwWY8jBN2FZza8P8nN2uLpCDE5wZb/PPHQ+3/h4adkXF6uv+FQScegW7tgGkNXnTR0D5uN2XlerUFRX8KTbpM6VfLWD395e1YpUZiBMK6QZlbkyyEz6BgW2/z/+TvXLYnEzNC0Viyb0wHSDq6IkVaetIrKDPjqW8rGkCDTtE4P2pwtGMP6rB38otZgNMFBW1sMdpFtBRuwVAek3i41ayl0hr/uLKdBydgfDunRXmwYoSyEPbF4ASU/4qrTkus0lFvTfjyieKGXl8YYqcnLWXPCvHNQj2eQHbGnuYUj+/o1Ce0oM+8aKFUv54e7HlCDOR/1WT+Bs=
